server:
  port: 6006

spring:
  application:
    name: interview-service
  datasource:
    url: jdbc:postgresql://103.182.211.219:5432/aibot
    username: aibot
    password: aibot!@#$%
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: interview_svc
  flyway:
    schemas: interview_svc
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6009/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

app:
  jwt:
    secret: dev-jwt-secret-change-in-production-min-32-chars
