version: '3.8'

services:
  aibot-postgres:
    image: postgres:15-alpine
    container_name: aibot-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: aibot
      POSTGRES_PASSWORD: 'aibot!@#$%'
      POSTGRES_DB: aibot
    volumes:
      - aibot_data:/var/lib/postgresql/data
    networks:
      - aibot-network
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: aibot-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@benchreadiness.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - aibot-network
    depends_on:
      - aibot-postgres
    restart: always

networks:
  aibot-network:
    external: true

volumes:
  aibot_data:
