server:
  port: 6008

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:postgresql://localhost:3308/bench_readiness
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: review_svc
  flyway:
    schemas: review_svc
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6009/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

feign:
  httpclient:
    hc5:
      enabled: true

app:
  jwt:
    secret: dev-jwt-secret-change-in-production-min-32-chars
